export let kanbanData: Object[] = [
  {
    Id: 'Task 1',
    Title: 'Design Microservices Architecture',
    Status: 'Open',
    Summary: 'Design the overall architecture for the microservices setup.',
    Type: 'Story',
    Priority: 'High',
    Tags: 'Architecture,Design',
    Estimate: 5,
    Assignee: 'Nancy Davloio',
    RankId: 1,
    Color: '#02897B',
    ClassName: 'e-story, e-high, e-nancy-davloio',
  },
  {
    Id: 'Task 2',
    Title: 'Setup Docker Environment',
    Status: 'InProgress',
    Summary: 'Set up the Docker environment for deploying microservices.',
    Type: 'Task',
    Priority: 'Normal',
    Tags: 'Docker,Setup',
    Estimate: 3,
    Assignee: 'Andrew Fuller',
    RankId: 1,
    Color: '#673AB8',
    ClassName: 'e-task, e-normal, e-andrew-fuller',
  },
  {
    Id: 'Task 3',
    Title: 'Implement API Gateway',
    Status: 'Open',
    Summary: 'Implement an API Gateway for routing to various microservices.',
    Type: 'Story',
    Priority: 'Critical',
    Tags: 'API Gateway,Implementation',
    Estimate: 4,
    Assignee: 'Janet Leverling',
    RankId: 2,
    Color: '#1F88E5',
    ClassName: 'e-story, e-critical, e-janet-leverling',
  },
  {
    Id: 'Task 4',
    Title: 'Develop Authentication Service',
    Status: 'InProgress',
    Summary: 'Develop a user authentication service for secure access.',
    Type: 'Story',
    Priority: 'High',
    Tags: 'Authentication,Service',
    Estimate: 6,
    Assignee: 'Margaret Hamilt',
    RankId: 2,
    Color: '#E64A19',
    ClassName: 'e-story, e-high, e-margaret-hamilt',
  },
  {
    Id: 'Task 5',
    Title: 'Test Inter-Service Communication',
    Status: 'Testing',
    Summary: 'Conduct tests for inter-service communication and data exchange.',
    Type: 'Testing',
    Priority: 'Normal',
    Tags: 'Communication,Testing',
    Estimate: 3.5,
    Assignee: 'Steven Walker',
    RankId: 1,
    Color: '#E64A19',
    ClassName: 'e-testing, e-normal, e-steven-walker',
  },
  {
    Id: 'Task 6',
    Title: 'Database Interaction Optimization',
    Status: 'Close',
    Summary: 'Review and optimize the database interactions for efficiency.',
    Type: 'Improvement',
    Priority: 'Low',
    Tags: 'Database,Optimization',
    Estimate: 2,
    Assignee: 'Michael Suyama',
    RankId: 1,
    Color: '#673AB8',
    ClassName: 'e-improvement, e-low, e-michael-suyama',
  },
  {
    Id: 'Task 7',
    Title: 'Validate Kubernetes Orchestration',
    Status: 'Validate',
    Summary:
      'Ensure the proper functioning of container orchestration with Kubernetes.',
    Type: 'Validation',
    Priority: 'High',
    Tags: 'Kubernetes,Orchestration',
    Estimate: 4.5,
    Assignee: 'Robert King',
    RankId: 1,
    Color: '#1F88E5',
    ClassName: 'e-validation, e-high, e-robert-king',
  },
  {
    Id: 'Task 8',
    Title: 'Create Monitoring Dashboard',
    Status: 'Open',
    Summary:
      'Develop a dashboard for monitoring microservices health and performance.',
    Type: 'Task',
    Priority: 'Normal',
    Tags: 'Monitoring,Dashboard',
    Estimate: 3,
    Assignee: 'Laura Callahan',
    RankId: 2,
    Color: '#02897B',
    ClassName: 'e-task, e-normal, e-laura-callahan',
  },
];
